[
  {
    name: "Spl. Ice Cream",
    description: "Special Ice Cream",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Fried Ice Cream",
    description: "Fried Ice Cream",
    price: 140,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Fruit Salad",
    description: "Fresh Fruit Salad",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 7,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Fruit Salad with Ice Cream",
    description: "Fruit Salad served with Ice Cream",
    price: 140,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Triple Sundae",
    description: "Triple Sundae Ice Cream",
    price: 180,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Gulab Jamun",
    description: "Gulab Jamun",
    price: 60,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Gulab Jamun with Ice Cream",
    description: "Gulab Jamun served with Ice Cream",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Gahu Roti",
    description: "Soft and wholesome whole wheat roti, freshly prepared.",
    price: 18,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Gahu Butter Roti",
    description: "Whole wheat roti topped with a generous layer of butter.",
    price: 25,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Plain Nan",
    description: "Classic soft naan, lightly baked for a fluffy texture.",
    price: 30,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 7,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Butter Nan",
    description: "Soft naan brushed with rich melted butter for extra flavor.",
    price: 40,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 7,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Plain Kulcha",
    description: "Traditional kulcha, soft inside with a lightly crisp exterior.",
    price: 30,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 7,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Butter Kulcha",
    description: "Warm kulcha finished with melted butter for a rich taste.",
    price: 40,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 7,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Plain Paratha",
    description: "Layered paratha cooked golden on the tawa.",
    price: 30,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Butter Paratha",
    description: "Flaky paratha topped with butter for a comforting bite.",
    price: 40,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cheese Garlic Nan",
    description: "Naan stuffed with cheese and infused with aromatic garlic.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Garlic Butter Nan",
    description: "Soft naan topped with garlic and melted butter.",
    price: 70,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 9,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Plain Aloo Paratha",
    description: "Paratha stuffed with mildly spiced mashed potatoes.",
    price: 60,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cheese Aloo Paratha",
    description: "Aloo paratha loaded with gooey cheese for extra indulgence.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Plain Paneer Paratha",
    description: "Paratha stuffed with fresh, lightly seasoned paneer.",
    price: 70,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Butter Paneer Paratha",
    description: "Paneer paratha finished with butter for rich flavor.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Paneer Cheese Paratha",
    description: "A delicious fusion of paneer and cheese in a flaky paratha.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 14,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Stuff Paratha",
    description: "Paratha stuffed with a flavorful mix of vegetables.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Butter Veg Stuff Paratha",
    description: "Veg stuffed paratha enriched with butter for added taste.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 13,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Cheese Stuff Paratha",
    description: "Vegetable and cheese stuffing wrapped in a crispy paratha.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Basket Roti",
    description: "Assorted basket of freshly prepared rotis, perfect for sharing.",
    price: 350,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 20,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cold Coffee",
    description: "Chilled and refreshing coffee blended to a smooth perfection.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cold Coffee with Ice Cream",
    description: "Rich cold coffee topped with a scoop of creamy ice cream.",
    price: 110,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 6,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Fresh Lime Soda (Sweet / Salt)",
    description: "Refreshing lime soda served sweet or salted to suit your taste.",
    price: 60,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 4,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Choice of Juice",
    description: "Freshly prepared juice made from seasonal fruits of your choice.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Mango Juice",
    description: "Sweet and pulpy mango juice made from ripe mangoes.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Choice of Milk Shake",
    description: "Creamy milkshake available in a variety of delicious flavors.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 6,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Dry Fruit Milk Shake",
    description: "Thick and rich milkshake blended with premium dry fruits.",
    price: 150,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Lassi",
    description: "Traditional chilled lassi, smooth and refreshing.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 4,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Lassi with Ice Cream",
    description: "Classic lassi served with a scoop of creamy ice cream.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Mango Lassi",
    description: "Sweet mango blended with creamy curd for a refreshing drink.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Dry Fruit Mastani",
    description: "Royal Mastani loaded with dry fruits and rich flavors.",
    price: 180,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Mastani",
    description: "Classic thick Mastani topped with ice cream and nuts.",
    price: 150,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 7,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Soft Drink",
    description: "Chilled soft drink served refreshing and fizzy.",
    price: 25,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 2,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Soda",
    description: "Plain chilled soda, perfect as a refreshing mixer.",
    price: 20,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 2,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Mineral Water",
    description: "Pure and chilled mineral water to keep you hydrated.",
    price: 20,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 1,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Pohe / Upma Sheera",
    description: "Light and comforting breakfast choice served fresh and warm.",
    price: 50,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Idli Sambar",
    description: "Soft steamed idlis served with flavorful sambar.",
    price: 70,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Udid Wada Sambar",
    description: "Crispy udid vadas soaked with hot, aromatic sambar.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Batata Wada Sambar",
    description: "Golden potato wada served with traditional sambar.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Plain Dosa",
    description: "Crispy dosa made from fermented rice batter.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Butter Plain Dosa",
    description: "Classic plain dosa cooked with butter for extra crispness.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Masala Dosa",
    description: "Crispy dosa stuffed with mildly spiced potato masala.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Paper Plain Dosa",
    description: "Extra thin and crispy paper-style plain dosa.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Butter Paper Plain Dosa",
    description: "Paper dosa roasted with butter for rich crunch.",
    price: 110,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Butter Paper Masala Dosa",
    description: "Large crispy paper dosa filled with buttery potato masala.",
    price: 140,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Paper Masala Dosa",
    description: "Thin and crisp paper dosa with classic masala filling.",
    price: 130,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cheese Masala Dosa",
    description: "Masala dosa layered with melted cheese for indulgence.",
    price: 110,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 14,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cheese Paper Masala Dosa",
    description: "Crispy paper dosa stuffed with masala and rich cheese.",
    price: 140,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 16,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cut Masala Dosa",
    description: "Masala dosa cut into pieces, perfect for sharing.",
    price: 110,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Mysore Plain Dosa",
    description: "Spicy Mysore-style dosa with red chutney spread.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Mysore Masala Dosa",
    description: "Mysore dosa filled with spicy potato masala.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Rava Masala Dosa",
    description: "Crispy rava dosa stuffed with flavorful masala.",
    price: 120,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 14,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Rava Plain Dosa",
    description: "Thin and crispy rava dosa with aromatic spices.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Plain Uttappa",
    description: "Soft and fluffy uttappa topped lightly with onions.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Onion Uttappa",
    description: "Uttappa topped generously with fresh onions.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Onion Masala Uttappa",
    description: "Thick uttappa topped with onion and mild masala.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Onion Butter Uttappa",
    description: "Soft uttappa topped with onions and butter.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Onion Cheese Uttappa",
    description: "Uttappa topped with onions and melted cheese.",
    price: 110,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 13,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Tomato Omelet",
    description: "South Indian style tomato omelet made on dosa batter.",
    price: 100,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Misal",
    description: "Traditional Maharashtrian misal with spicy gravy.",
    price: 70,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 3,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Dahi Misal",
    description: "Misal topped with fresh curd for a balanced flavor.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 12,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Kanda Bhaji",
    description: "Crispy onion fritters served hot.",
    price: 60,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Gol Bhaji",
    description: "Deep-fried round bhajis, crispy outside and soft inside.",
    price: 50,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 1,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Green Salad",
    description: "Freshly cut seasonal vegetables tossed lightly for a refreshing start.",
    price: 60,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Raita",
    description: "Cool and creamy curd mixed with fresh vegetables and mild spices.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Boondi Raita",
    description: "Classic raita with crispy boondi blended into fresh curd.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Pineapple Raita",
    description: "Sweet and tangy pineapple raita with chilled curd.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "French Fries",
    description: "Crispy golden fries served hot and lightly salted.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Masala Papad",
    description: "Crunchy papad topped with onions, tomatoes, and Indian spices.",
    price: 40,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 5,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Papad Fry",
    description: "Deep-fried papad served crisp and crunchy.",
    price: 30,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 3,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Roast Papad",
    description: "Lightly roasted papad for a healthier crunch.",
    price: 20,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 2,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Sweet Corn Soup",
    description: "Warm and comforting soup made with sweet corn kernels.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Manchow Soup",
    description: "Spicy and flavorful soup topped with crispy noodles.",
    price: 99,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 2,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Hot & Sour Soup",
    description: "Bold and tangy soup with a perfect balance of heat and sourness.",
    price: 99,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: false,
    spice_level: 2,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cream of Veg Soup",
    description: "Smooth and creamy soup blended with fresh vegetables.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 9,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cream of Tomato Soup",
    description: "Rich and velvety tomato soup with a creamy finish.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 9,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Cream of Mushroom Soup",
    description: "Creamy mushroom soup with earthy flavors and smooth texture.",
    price: 99,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 10,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Palak Soup",
    description: "Healthy spinach soup packed with nutrients and mild spices.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 0,
    prep_time_minutes: 8,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Clear Soup",
    description: "Light and clear vegetable soup, perfect as a starter.",
    price: 80,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 7,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Coriander Soup",
    description: "Aromatic soup infused with fresh coriander and gentle spices.",
    price: 90,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 7,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Anda Kari",
    description: "A unique vegetarian twist with rich gravy and soft veg ‘anda’ balls simmered in spices.",
    price: 180,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Surmai",
    description: "Chef-special vegetable curry inspired by coastal Surmai-style masala.",
    price: 180,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Cheese Ball Handi",
    description: "Soft cheese balls cooked in a creamy, mildly spiced handi gravy.",
    price: 220,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 18,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Chilli Milli",
    description: "Colorful mix of vegetables tossed in a tangy and mildly spicy gravy.",
    price: 200,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Tawa",
    description: "Assorted vegetables cooked on a tawa with bold spices and butter.",
    price: 200,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 16,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Angara",
    description: "Smoky and spicy vegetable curry with rich Angara-style masala.",
    price: 250,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 3,
    prep_time_minutes: 18,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Peshawari",
    description: "Creamy and mildly sweet curry inspired by Peshawari flavors.",
    price: 200,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 17,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Patiyala",
    description: "Royal Punjabi-style vegetable curry with thick, rich gravy.",
    price: 250,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 18,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Maratha",
    description: "Traditional Maharashtrian-style veg curry with bold local spices.",
    price: 190,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Lahori",
    description: "Rich North Indian vegetable curry with aromatic Lahori masala.",
    price: 190,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Mix Veg",
    description: "Classic mixed vegetable curry cooked in homestyle gravy.",
    price: 180,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 14,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Kolhapuri",
    description: "Spicy Kolhapuri-style veg curry packed with bold flavors.",
    price: 190,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 3,
    prep_time_minutes: 16,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Kadhai",
    description: "Vegetables cooked with capsicum and onions in kadhai masala.",
    price: 180,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 15,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Hyderabadi",
    description: "Aromatic Hyderabadi-style veg curry with rich spices.",
    price: 190,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    spice_level: 2,
    prep_time_minutes: 16,
    created_at: "2026-02-06T00:00:00.000Z"
  },
  {
    name: "Veg Handi",
    description: "Traditional handi-cooked vegetable curry with thick, flavorful gravy.",
    price: 190,
    category_id: 1,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    spice_level: 1,
    prep_time_minutes: 16,
    created_at: "2026-02-06T00:00:00.000Z"
  }
]








