import { Category, MenuItem, Table, Order } from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Dessert",
    description: "Ice creams and desserts",
    image_url: "/images/dessert.jpg",
    display_order: 1,
    is_active: true,
  },
  {
    id: "2",
    name: "Roti",
    description: "Roti, naan, kulcha, paratha",
    image_url: "/images/roti.jpg",
    display_order: 2,
    is_active: true,
  },
  {
    id: "3",
    name: "Beverage",
    description: "Cold drinks and beverages",
    image_url: "/images/beverage.jpg",
    display_order: 3,
    is_active: true,
  },
  {
    id: "4",
    name: "South Indian",
    description: "South Indian dishes",
    image_url: "/images/south-indian.jpg",
    display_order: 4,
    is_active: true,
  },
  {
    id: "5",
    name: "Salad",
    description: "Salads and raita",
    image_url: "/images/salad.jpg",
    display_order: 5,
    is_active: true,
  },
  {
    id: "6",
    name: "Soup",
    description: "Hot soups",
    image_url: "/images/soup.jpg",
    display_order: 6,
    is_active: true,
  },
  {
    id: "7",
    name: "Veg Main Course",
    description: "Indian veg curries",
    image_url: "/images/veg-main.jpg",
    display_order: 7,
    is_active: true,
  },
  {
    id: "8",
    name: "Rice",
    description: "Rice and biryani dishes",
    image_url: "/images/rice.jpg",
    display_order: 8,
    is_active: true,
  },
  {
    id: "9",
    name: "Dal",
    description: "Dal preparations",
    image_url: "/images/dal.jpg",
    display_order: 9,
    is_active: true,
  },
  {
    id: "10",
    name: "Starters",
    description: "Indian starters",
    image_url: "/images/starters.jpg",
    display_order: 10,
    is_active: true,
  },
  {
    id: "11",
    name: "Chinese Starters",
    description: "Indo-Chinese starters",
    image_url: "/images/chinese.jpg",
    display_order: 11,
    is_active: true,
  },
  {
    id: "12",
    name: "Tandoori Starter",
    description: "Tandoori & kebabs",
    image_url: "/images/tandoori.jpg",
    display_order: 12,
    is_active: true,
  },
  {
    id: "13",
    name: "Indian Special Dish",
    description: "Special veg gravies",
    image_url: "/images/indian-special.jpg",
    display_order: 13,
    is_active: true,
  },
];

export const menuItems: MenuItem[] = [
  {
    id: "1",
    category_id: "1",
    name: "Special Ice Cream",
    description: "Special Ice Cream",
    price: 80,
    image_url: "/images/special-ice-cream.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 1,
  },
  {
    id: "2",
    category_id: "1",
    name: "Fried Ice Cream",
    description: "Fried Ice Cream",
    price: 140,
    image_url: "/images/fried-ice-cream.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 2,
  },
  {
    id: "3",
    category_id: "1",
    name: "Fruit Salad",
    description: "Fruit Salad",
    price: 100,
    image_url: "/images/fruit-salad.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 3,
  },
  {
    id: "4",
    category_id: "1",
    name: "Triple Sundae",
    description: "Triple Sundae",
    price: 180,
    image_url: "/images/triple-sundae.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 4,
  },
  {
    id: "5",
    category_id: "1",
    name: "Gulab Jamun",
    description: "Gulab Jamun",
    price: 60,
    image_url: "/images/gulab-jamun.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 5,
  },
  {
    id: "6",
    category_id: "1",
    name: "Gulab Jamun with Ice Cream",
    description: "Gulab Jamun with Ice Cream",
    price: 90,
    image_url: "/images/gulab-jamun-with-ice-cream.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 6,
  },
  {
    id: "7",
    category_id: "2",
    name: "Gahu Roti",
    description: "Gahu Roti",
    price: 18,
    image_url: "/images/gahu-roti.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 7,
  },
  {
    id: "8",
    category_id: "2",
    name: "Butter Roti",
    description: "Butter Roti",
    price: 25,
    image_url: "/images/butter-roti.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 8,
  },
  {
    id: "9",
    category_id: "2",
    name: "Plain Naan",
    description: "Plain Naan",
    price: 30,
    image_url: "/images/plain-naan.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 9,
  },
  {
    id: "10",
    category_id: "2",
    name: "Butter Naan",
    description: "Butter Naan",
    price: 40,
    image_url: "/images/butter-naan.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 10,
  },
  {
    id: "11",
    category_id: "2",
    name: "Plain Kulcha",
    description: "Plain Kulcha",
    price: 30,
    image_url: "/images/plain-kulcha.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 11,
  },
  {
    id: "12",
    category_id: "2",
    name: "Butter Kulcha",
    description: "Butter Kulcha",
    price: 40,
    image_url: "/images/butter-kulcha.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 12,
  },
  {
    id: "13",
    category_id: "8",
    name: "Jeera Rice Half",
    description: "Jeera Rice Half",
    price: 70,
    image_url: "/images/jeera-rice-half.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 13,
  },
  {
    id: "14",
    category_id: "8",
    name: "Jeera Rice Full",
    description: "Jeera Rice Full",
    price: 120,
    image_url: "/images/jeera-rice-full.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 14,
  },
  {
    id: "15",
    category_id: "8",
    name: "Steam Rice Half",
    description: "Steam Rice Half",
    price: 60,
    image_url: "/images/steam-rice-half.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 15,
  },
  {
    id: "16",
    category_id: "8",
    name: "Steam Rice Full",
    description: "Steam Rice Full",
    price: 100,
    image_url: "/images/steam-rice-full.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 16,
  },
  {
    id: "17",
    category_id: "8",
    name: "Veg Biryani Half",
    description: "Veg Biryani Half",
    price: 120,
    image_url: "/images/veg-biryani-half.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 17,
  },
  {
    id: "18",
    category_id: "8",
    name: "Veg Biryani Full",
    description: "Veg Biryani Full",
    price: 180,
    image_url: "/images/veg-biryani-full.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 18,
  },
  {
    id: "19",
    category_id: "9",
    name: "Dal Fry",
    description: "Dal Fry",
    price: 120,
    image_url: "/images/dal-fry.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 19,
  },
  {
    id: "20",
    category_id: "9",
    name: "Dal Tadka",
    description: "Dal Tadka",
    price: 140,
    image_url: "/images/dal-tadka.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 20,
  },
  {
    id: "21",
    category_id: "9",
    name: "Dal Kolhapuri",
    description: "Dal Kolhapuri",
    price: 130,
    image_url: "/images/dal-kolhapuri.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 21,
  },
  {
    id: "22",
    category_id: "7",
    name: "Veg Kolhapuri",
    description: "Veg Kolhapuri",
    price: 190,
    image_url: "/images/veg-kolhapuri.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 22,
  },
  {
    id: "23",
    category_id: "7",
    name: "Veg Handi",
    description: "Veg Handi",
    price: 200,
    image_url: "/images/veg-handi.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 23,
  },
  {
    id: "24",
    category_id: "7",
    name: "Paneer Butter Masala",
    description: "Paneer Butter Masala",
    price: 220,
    image_url: "/images/paneer-butter-masala.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 24,
  },
  {
    id: "25",
    category_id: "7",
    name: "Shahi Paneer",
    description: "Shahi Paneer",
    price: 230,
    image_url: "/images/shahi-paneer.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 25,
  },
  {
    id: "26",
    category_id: "7",
    name: "Veg Tiranga",
    description: "Veg Tiranga",
    price: 300,
    image_url: "/images/veg-tiranga.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 26,
  },
  {
    id: "27",
    category_id: "10",
    name: "Paneer Chilli",
    description: "Paneer Chilli",
    price: 180,
    image_url: "/images/paneer-chilli.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 27,
  },
  {
    id: "28",
    category_id: "10",
    name: "Paneer 65",
    description: "Paneer 65",
    price: 190,
    image_url: "/images/paneer-65.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 28,
  },
  {
    id: "29",
    category_id: "10",
    name: "Veg Crispy",
    description: "Veg Crispy",
    price: 170,
    image_url: "/images/veg-crispy.jpg",
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    spice_level: 0,
    preparation_time: 10,
    display_order: 29,
  },
];


export const tables: Table[] = [
  { id: '1', table_number: 'T1', capacity: 2, status: 'available', location: 'Window' },
  { id: '2', table_number: 'T2', capacity: 2, status: 'occupied', location: 'Window' },
  { id: '3', table_number: 'T3', capacity: 4, status: 'available', location: 'Main Hall' },
  { id: '4', table_number: 'T4', capacity: 4, status: 'reserved', location: 'Main Hall' },
  { id: '5', table_number: 'T5', capacity: 6, status: 'available', location: 'Main Hall' },
  { id: '6', table_number: 'T6', capacity: 6, status: 'occupied', location: 'Patio' },
  { id: '7', table_number: 'T7', capacity: 8, status: 'available', location: 'Private Room' },
  { id: '8', table_number: 'T8', capacity: 4, status: 'available', location: 'Patio' },
]

export const orders: Order[] = [
  {
    id: '1',
    order_number: 'ORD-001',
    customer_name: 'John Smith',
    customer_phone: '+1 555-0123',
    customer_email: 'john@example.com',
    order_type: 'takeaway',
    items: [
      { id: '1', menu_item_id: '5', menu_item_name: 'Grilled Ribeye Steak', quantity: 2, unit_price: 38.99, total_price: 77.98 },
      { id: '2', menu_item_id: '2', menu_item_name: 'Bruschetta Trio', quantity: 1, unit_price: 12.99, total_price: 12.99 },
    ],
    subtotal: 90.97,
    tax: 9.10,
    total: 100.07,
    status: 'preparing',
    estimated_ready_time: '7:30 PM',
    created_at: '2026-02-02T18:45:00Z',
    updated_at: '2026-02-02T18:50:00Z',
  },
  {
    id: '2',
    order_number: 'ORD-002',
    customer_name: 'Sarah Johnson',
    customer_phone: '+1 555-0456',
    order_type: 'dine-in',
    table_id: '2',
    items: [
      { id: '3', menu_item_id: '6', menu_item_name: 'Pan-Seared Salmon', quantity: 1, unit_price: 32.99, total_price: 32.99 },
      { id: '4', menu_item_id: '7', menu_item_name: 'Wild Mushroom Risotto', quantity: 1, unit_price: 24.99, total_price: 24.99 },
      { id: '5', menu_item_id: '14', menu_item_name: 'Iced Coffee', quantity: 2, unit_price: 4.99, total_price: 9.98 },
    ],
    subtotal: 67.96,
    tax: 6.80,
    total: 74.76,
    status: 'confirmed',
    created_at: '2026-02-02T19:00:00Z',
    updated_at: '2026-02-02T19:00:00Z',
  },
  {
    id: '3',
    order_number: 'ORD-003',
    customer_name: 'Mike Davis',
    customer_phone: '+1 555-0789',
    order_type: 'takeaway',
    items: [
      { id: '6', menu_item_id: '9', menu_item_name: 'Classic Burger', quantity: 3, unit_price: 19.99, total_price: 59.97 },
      { id: '7', menu_item_id: '13', menu_item_name: 'Fresh Lemonade', quantity: 3, unit_price: 5.99, total_price: 17.97 },
    ],
    subtotal: 77.94,
    tax: 7.79,
    total: 85.73,
    status: 'ready',
    estimated_ready_time: '7:15 PM',
    created_at: '2026-02-02T18:30:00Z',
    updated_at: '2026-02-02T19:10:00Z',
  },
  {
    id: '4',
    order_number: 'ORD-004',
    customer_name: 'Emily Chen',
    customer_phone: '+1 555-0321',
    order_type: 'dine-in',
    table_id: '6',
    items: [
      { id: '8', menu_item_id: '8', menu_item_name: 'Thai Green Curry', quantity: 2, unit_price: 22.99, total_price: 45.98 },
      { id: '9', menu_item_id: '10', menu_item_name: 'Chocolate Lava Cake', quantity: 2, unit_price: 12.99, total_price: 25.98 },
    ],
    subtotal: 71.96,
    tax: 7.20,
    total: 79.16,
    status: 'completed',
    created_at: '2026-02-02T17:00:00Z',
    updated_at: '2026-02-02T18:30:00Z',
  },
]
